// ============================================================
// LÍNEA DE TIEMPO — Colombia y el Mundo (1860–2026)
// ============================================================

const GLOSARIO = {
  "federalismo": "Sistema político en el que el poder se reparte entre un gobierno central y estados o provincias con amplia autonomía para gobernarse a sí mismos.",
  "liberales radicales": "Ala más reformista del Partido Liberal colombiano del siglo XIX, partidaria de la separación Iglesia–Estado, la educación laica y los gobiernos regionales fuertes.",
  "Regeneración": "Movimiento político liderado por Rafael Núñez desde 1880 que buscó centralizar el poder del Estado colombiano, debilitando el federalismo radical.",
  "hegemonía conservadora": "Período de más de 40 años (1886–1930) en que el Partido Conservador controló de forma casi ininterrumpida la presidencia de Colombia.",
  "Revolución en Marcha": "Programa de reformas sociales, agrarias y laborales impulsado por el presidente Alfonso López Pumarejo a partir de 1934.",
  "Bogotazo": "Estallido de violencia y disturbios en Bogotá tras el asesinato de Jorge Eliécer Gaitán en 1948, que se extendió a otras regiones del país.",
  "La Violencia": "Período de conflicto armado entre liberales y conservadores en Colombia, especialmente intenso entre 1948 y mediados de los años 1950.",
  "Frente Nacional": "Acuerdo político (1958–1974) mediante el cual liberales y conservadores se alternaron la presidencia y repartieron cargos públicos para poner fin a La Violencia.",
  "FARC": "Fuerzas Armadas Revolucionarias de Colombia, grupo guerrillero de izquierda surgido en 1964, protagonista central del conflicto armado colombiano.",
  "Asamblea Constituyente": "Cuerpo de representantes electos para redactar o reformar la constitución de un país; en Colombia dio lugar a la Carta de 1991.",
  "Plan Colombia": "Estrategia de cooperación entre Colombia y Estados Unidos, iniciada en 2000, orientada a combatir el narcotráfico y fortalecer las instituciones de seguridad.",
  "Seguridad Democrática": "Política del gobierno de Álvaro Uribe Vélez (2002–2010) centrada en recuperar el control militar del territorio frente a grupos armados ilegales.",
  "Operación Jaque": "Operación militar de inteligencia colombiana en 2008 que permitió rescatar a varios secuestrados en poder de las FARC sin disparar un tiro.",
  "paz total": "Política del gobierno de Gustavo Petro orientada a negociar simultáneamente con distintos grupos armados ilegales para poner fin al conflicto en Colombia.",
  "Guerra Civil estadounidense": "Conflicto armado (1861–1865) entre los estados del norte y del sur de Estados Unidos, motivado en gran parte por la esclavitud.",
  "Proclamación de Emancipación": "Decreto de Abraham Lincoln (1863) que declaró libres a los esclavos de los estados en rebelión contra la Unión.",
  "Restauración Meiji": "Proceso de modernización política, militar e industrial de Japón iniciado en 1868 que lo transformó en potencia mundial.",
  "unificación de Alemania": "Proceso por el cual los distintos estados alemanes se integraron en un solo Imperio Alemán, completado en 1871 bajo el liderazgo de Prusia.",
  "Triple Alianza": "Alianza militar formada en 1882 entre Alemania, Austria-Hungría e Italia, antecedente de los bloques de la Primera Guerra Mundial.",
  "Conferencia de Berlín": "Reunión de potencias europeas (1884–1885) en la que se establecieron reglas para repartirse y colonizar el continente africano.",
  "Año de los Tres Emperadores": "1888, año en que Alemania tuvo tres emperadores distintos debido a la muerte sucesiva de Guillermo I y Federico III.",
  "Alianza Anglo-Japonesa": "Tratado de 1902 entre el Reino Unido y Japón que reforzó la posición de Japón como potencia en Asia.",
  "evento de Tunguska": "Enorme explosión ocurrida en 1908 en Siberia, atribuida al impacto o desintegración de un meteorito, que arrasó miles de kilómetros de bosque.",
  "Sociedad de Naciones": "Organización internacional creada en 1920 tras la Primera Guerra Mundial con el objetivo de mantener la paz mundial; antecesora de la ONU.",
  "gripe española": "Pandemia de influenza que entre 1918 y 1920 infectó a cientos de millones de personas en todo el mundo, incluida Colombia.",
  "Gran Depresión": "Crisis económica mundial iniciada en 1929 que provocó desempleo masivo y pobreza generalizada durante la década de 1930.",
  "Acuerdos de Múnich": "Pacto de 1938 mediante el cual Alemania anexó parte de Checoslovaquia, considerado un fracaso de la política de apaciguamiento frente al nazismo.",
  "desembarco de Normandía": "Operación militar aliada de junio de 1944 en las playas de Normandía, Francia, clave para la liberación de Europa occidental del dominio nazi.",
  "Crisis de los Misiles de Cuba": "Enfrentamiento de 1962 entre Estados Unidos y la Unión Soviética por el despliegue de misiles soviéticos en Cuba, uno de los momentos más tensos de la Guerra Fría.",
  "Acuerdos de Camp David": "Tratados de 1978 negociados entre Egipto e Israel que sentaron las bases para la paz entre ambos países.",
  "desastre de Chernóbil": "Accidente nuclear ocurrido en 1986 en Ucrania (entonces URSS), uno de los mayores desastres nucleares de la historia.",
  "Apartheid": "Sistema de segregación racial institucionalizado en Sudáfrica, vigente hasta su abolición formal en 1994.",
  "Brexit": "Proceso de salida del Reino Unido de la Unión Europea, aprobado por referéndum en 2016."
};

const TIMELINE = [
  { year: 1860,
    colombia: { title: "Guerra de las Soberanías", category: "Política",
      text: "Comienza la Guerra de las Soberanías, un conflicto armado entre el gobierno conservador de Mariano Ospina Rodríguez y los líderes liberales que defendían el [[federalismo]]. Los liberales se oponían al aumento del poder del gobierno central y buscaban que los estados conservaran su autonomía. La guerra se extendió por gran parte del territorio nacional y tuvo importantes consecuencias políticas." },
    mundo: { title: "Lincoln y el preludio de la Guerra Civil", category: "Política",
      text: "Fue elegido Abraham Lincoln como presidente de Estados Unidos, lo que aumentó las tensiones entre el norte y el sur y llevó al inicio de la [[Guerra Civil estadounidense]]. Además, la Revolución Industrial seguía impulsando importantes avances tecnológicos y económicos en varias partes del mundo." } },
  { year: 1862,
    colombia: { title: "Triunfo liberal de Mosquera", category: "Política",
      text: "La guerra termina con la victoria de los liberales liderados por Tomás Cipriano de Mosquera. Su triunfo permitió iniciar profundas reformas políticas, económicas y religiosas. Además, marcó el debilitamiento del poder conservador y preparó el camino para la creación de un sistema federal en Colombia." },
    mundo: { title: "Estalla la Guerra Civil estadounidense", category: "Conflicto",
      text: "Comienza la [[Guerra Civil estadounidense]], uno de los conflictos más importantes del siglo XIX, tras la separación de varios estados del sur de Estados Unidos. Ese mismo año, Abraham Lincoln asumió la presidencia del país." } },
  { year: 1864,
    colombia: { title: "Los Estados Unidos de Colombia", category: "Política",
      text: "Los Estados Unidos de Colombia continúan organizándose bajo el modelo [[federalismo|federal]] establecido por la Constitución de 1863. Cada estado gozaba de una amplia autonomía para tomar decisiones sobre sus asuntos internos. El gobierno nacional tenía funciones limitadas, principalmente en relaciones exteriores y defensa." },
    mundo: { title: "La Proclamación de Emancipación entra en vigor", category: "Sociedad",
      text: "Entró en vigor la [[Proclamación de Emancipación]] de Abraham Lincoln, que liberó a los esclavos de los estados rebeldes. Abraham Lincoln fue reelegido presidente, fortaleciendo la lucha por mantener unido el país y abolir la esclavitud." } },
  { year: 1866,
    colombia: { title: "Mosquera, presidente constitucional", category: "Política",
      text: "Tomás Cipriano de Mosquera es elegido presidente constitucional de los Estados Unidos de Colombia. Durante su gobierno continuó promoviendo las ideas [[liberales radicales]], fortaleciendo la separación entre la Iglesia y el Estado y defendiendo el sistema federal. Su administración también impulsó medidas para modernizar el país." },
    mundo: { title: "Prusia y el cable transatlántico", category: "Tecnología",
      text: "Prusia derrotó a Austria en la Guerra Austro-Prusiana, convirtiéndose en la principal potencia alemana. También se instaló con éxito el Cable Telegráfico Transatlántico, que permitió una comunicación mucho más rápida entre Europa y América." } },
  { year: 1868,
    colombia: { title: "Tensiones bajo el federalismo", category: "Política",
      text: "Colombia atraviesa un período de consolidación de los Estados Unidos de Colombia. Aunque el sistema federal seguía vigente, existían tensiones entre distintos grupos políticos sobre el alcance de la autonomía de los estados. La economía dependía principalmente de la agricultura y del comercio exterior." },
    mundo: { title: "Restauración Meiji en Japón", category: "Política",
      text: "En el mundo, uno de los hechos más importantes fue el inicio de la [[Restauración Meiji]], que modernizó Japón. Además, continuó la expansión de la industria y los avances tecnológicos en Europa y América, impulsando el crecimiento económico y el desarrollo de nuevas formas de transporte y comunicación." } },
  { year: 1870,
    colombia: { title: "Reforma educativa liberal", category: "Educación",
      text: "Se impulsa una importante reforma educativa liberal. El gobierno promueve la educación pública, gratuita y laica con el objetivo de ampliar el acceso a la enseñanza y reducir la influencia de la Iglesia en la educación. Esta reforma generó apoyo entre los liberales, pero también una fuerte oposición de sectores conservadores." },
    mundo: { title: "Guerra Franco-Prusiana", category: "Conflicto",
      text: "Comenzó la Guerra Franco-Prusiana entre Francia y Prusia. Este conflicto fue decisivo para la [[unificación de Alemania]] y cambió el equilibrio de poder en Europa." } },
  { year: 1872,
    colombia: { title: "Expansión del sistema educativo", category: "Educación",
      text: "Continúa la expansión del sistema educativo en varias regiones del país. Se crean nuevas escuelas y se fortalece la formación de maestros. Estas medidas buscaban modernizar la sociedad colombiana y aumentar los niveles de alfabetización de la población." },
    mundo: { title: "Auge industrial y ferroviario", category: "Tecnología",
      text: "Continuó la expansión industrial y el desarrollo de los ferrocarriles y las comunicaciones en Europa y América." } },
  { year: 1874,
    colombia: { title: "Debate entre liberales y conservadores", category: "Política",
      text: "Persisten los debates entre liberales y conservadores sobre la educación, la religión y el papel del Estado. Mientras los liberales defendían reformas modernizadoras, los conservadores consideraban que muchas de ellas amenazaban las tradiciones religiosas y sociales del país." },
    mundo: { title: "Fortalecimiento del comercio internacional", category: "Economía",
      text: "Se fortalecieron las economías industriales y aumentó el comercio internacional entre las grandes potencias." } },
  { year: 1876,
    colombia: { title: "Nueva guerra civil", category: "Conflicto",
      text: "Estalla una nueva guerra civil debido a las tensiones políticas y religiosas acumuladas durante años. Uno de los principales motivos fue el rechazo conservador a las reformas educativas liberales. El conflicto afectó numerosas regiones y provocó una importante inestabilidad nacional." },
    mundo: { title: "Bell patenta el teléfono", category: "Tecnología",
      text: "Alexander Graham Bell patentó el teléfono, revolucionando las comunicaciones en el mundo." } },
  { year: 1878,
    colombia: { title: "Fin de la guerra civil", category: "Conflicto",
      text: "Finaliza la guerra civil y el país intenta recuperar la estabilidad. Aunque los enfrentamientos terminan, las diferencias entre liberales y conservadores continúan marcando la vida política colombiana. La reconstrucción económica y social se convierte en una prioridad." },
    mundo: { title: "Congreso de Berlín", category: "Política",
      text: "Se celebró el Congreso de Berlín, que reorganizó territorios en Europa y buscó mantener la paz entre las potencias." } },
  { year: 1880,
    colombia: { title: "Núñez y la Regeneración", category: "Política",
      text: "Llega a la presidencia Rafael Núñez, quien impulsa el movimiento de la [[Regeneración]]. Este buscaba fortalecer el gobierno central y reducir la autonomía de los estados federales. Sus ideas marcarían el rumbo político de Colombia durante las siguientes décadas." },
    mundo: { title: "Segunda Revolución Industrial", category: "Tecnología",
      text: "La Segunda Revolución Industrial impulsó avances en la electricidad, la industria y el transporte, transformando la vida cotidiana y la economía mundial." } },
  { year: 1882,
    colombia: { title: "Avance de la Regeneración", category: "Política",
      text: "La [[Regeneración]] gana cada vez más apoyo entre sectores conservadores y moderados. Se intensifican los debates sobre la necesidad de reformar el sistema federal y reorganizar las instituciones del país." },
    mundo: { title: "Se forma la Triple Alianza", category: "Política",
      text: "Se formó la [[Triple Alianza]], una importante alianza política y militar en Europa." } },
  { year: 1884,
    colombia: { title: "Aumentan las tensiones políticas", category: "Política",
      text: "Las tensiones políticas entre [[liberales radicales]] y conservadores aumentan considerablemente. Los conflictos desembocan en enfrentamientos armados en varias regiones del país." },
    mundo: { title: "Conferencia de Berlín", category: "Política",
      text: "Comenzó la [[Conferencia de Berlín]], donde las potencias europeas acordaron reglas para repartirse territorios en África." } },
  { year: 1886,
    colombia: { title: "Constitución de 1886 y centralismo", category: "Política",
      text: "Bajo el impulso de la [[Regeneración]], se consolida un nuevo orden constitucional centralista que pondría fin al modelo federal y daría inicio a la [[hegemonía conservadora]] que dominaría la política colombiana durante las siguientes cuatro décadas." },
    mundo: { title: "Se inaugura la Estatua de la Libertad", category: "Sociedad",
      text: "Se inauguró la Estatua de la Libertad, símbolo de libertad y amistad entre Francia y Estados Unidos." } },
  { year: 1888,
    colombia: { title: "Consolidación del nuevo régimen", category: "Política",
      text: "El régimen centralista nacido de la Regeneración se consolida en Colombia, mientras las diferencias entre los partidos tradicionales siguen latentes bajo la superficie de la nueva institucionalidad." },
    mundo: { title: "El Año de los Tres Emperadores", category: "Política",
      text: "Alemania tuvo el llamado “[[Año de los Tres Emperadores]]”, con tres cambios de emperador en pocos meses." } },
  { year: 1890,
    colombia: { title: "Continúa la hegemonía conservadora", category: "Política",
      text: "La [[hegemonía conservadora]] sigue consolidándose en Colombia, en un contexto de creciente malestar entre los sectores liberales excluidos del poder político." },
    mundo: { title: "Salida de Bismarck", category: "Política",
      text: "Alemania comenzó una nueva etapa política tras la salida del canciller Otto von Bismarck, una de las figuras más influyentes de Europa en el siglo XIX." } },
  { year: 1892,
    colombia: { title: "Tensión política persistente", category: "Política",
      text: "El descontento liberal frente al modelo centralista de la Regeneración continúa creciendo, sentando las bases para los conflictos que estallarían hacia el final de la década." },
    mundo: { title: "Industrialización acelerada", category: "Economía",
      text: "Se fortaleció la industrialización y el crecimiento económico en Europa y Estados Unidos." } },
  { year: 1894,
    colombia: { title: "Crisis política en gestación", category: "Política",
      text: "Las diferencias entre liberales y conservadores se agudizan en distintas regiones del país, en un ambiente de creciente polarización que anticipa los enfrentamientos de fin de siglo." },
    mundo: { title: "Primera Guerra Sino-Japonesa", category: "Conflicto",
      text: "Comenzó la Primera Guerra Sino-Japonesa, que mostró el creciente poder de Japón en Asia." } },
  { year: 1896,
    colombia: { title: "Profundización de la crisis", category: "Política",
      text: "La crisis económica y política se profundiza en Colombia. Las diferencias entre liberales y conservadores son cada vez más marcadas, mientras aumentan las críticas al gobierno conservador. El descontento social crece debido a las dificultades económicas, la exclusión política de los liberales y la falta de soluciones a los problemas nacionales." },
    mundo: { title: "Primeros Juegos Olímpicos modernos", category: "Cultura",
      text: "Se celebraron los primeros Juegos Olímpicos de verano en Atenas, Grecia." } },
  { year: 1898,
    colombia: { title: "Al borde de la guerra", category: "Política",
      text: "Las tensiones políticas llegan a uno de sus puntos más altos. Los enfrentamientos entre liberales y conservadores se intensifican y muchos sectores consideran inevitable una guerra civil. La situación económica continúa deteriorándose, lo que contribuye al aumento de la inestabilidad en el país." },
    mundo: { title: "Guerra Hispano-Estadounidense", category: "Conflicto",
      text: "Ocurrió la Guerra Hispano-Estadounidense, que aumentó la influencia de Estados Unidos en el mundo." } },
  { year: 1900,
    colombia: { title: "Guerra de los Mil Días", category: "Conflicto",
      text: "La Guerra de los Mil Días se encuentra en pleno desarrollo. Este conflicto, considerado uno de los más devastadores de la historia colombiana, deja miles de muertos, destruye gran parte de la economía nacional y afecta gravemente la vida de la población. Los combates ocurren en distintas regiones del país." },
    mundo: { title: "Auge de la Segunda Revolución Industrial", category: "Tecnología",
      text: "La Segunda Revolución Industrial continuó impulsando grandes avances en la electricidad, la ciencia, el transporte y las comunicaciones." } },
  { year: 1902,
    colombia: { title: "Fin de la Guerra de los Mil Días", category: "Conflicto",
      text: "Finaliza la Guerra de los Mil Días con la firma de acuerdos de paz. Colombia queda profundamente debilitada, con graves pérdidas humanas, económicas y sociales. La reconstrucción del país se convierte en una prioridad para los gobiernos de comienzos del siglo XX." },
    mundo: { title: "Alianza Anglo-Japonesa", category: "Política",
      text: "Se firmó la [[Alianza Anglo-Japonesa]], fortaleciendo la influencia de Japón en Asia." } },
  { year: 1904,
    colombia: { title: "Reconstrucción nacional", category: "Economía",
      text: "El gobierno inicia programas de recuperación económica y reconstrucción nacional. Se busca restablecer el orden político y fortalecer la infraestructura del país después de los daños causados por la guerra." },
    mundo: { title: "Guerra Ruso-Japonesa", category: "Conflicto",
      text: "Comenzó la Guerra Ruso-Japonesa, un conflicto importante por el control de territorios en Asia." } },
  { year: 1906,
    colombia: { title: "Modernización de infraestructura", category: "Economía",
      text: "Se impulsan proyectos de modernización, especialmente en transporte, comunicaciones y obras públicas. Estas iniciativas buscan mejorar la integración del territorio nacional y promover el crecimiento económico." },
    mundo: { title: "Terremoto de San Francisco", category: "Desastre",
      text: "El terremoto de San Francisco de 1906 causó grandes daños y miles de víctimas en Estados Unidos." } },
  { year: 1908,
    colombia: { title: "Reformas administrativas", category: "Política",
      text: "Se realizan reformas administrativas para fortalecer el control del Estado sobre el territorio. También se busca mejorar la eficiencia del gobierno y modernizar algunas instituciones públicas." },
    mundo: { title: "El evento de Tunguska", category: "Desastre",
      text: "Se produjo la explosión del [[evento de Tunguska]] en Siberia, una de las mayores explosiones registradas en la historia." } },
  { year: 1910,
    colombia: { title: "Reforma constitucional democrática", category: "Política",
      text: "Una importante reforma constitucional introduce cambios democráticos y limita algunos poderes presidenciales. Además, se fortalecen mecanismos de participación política y se promueve una mayor estabilidad institucional." },
    mundo: { title: "Comienza la Revolución Mexicana", category: "Conflicto",
      text: "Comenzó la Revolución Mexicana, un importante movimiento político y social en América Latina." } },
  { year: 1912,
    colombia: { title: "El café como eje económico", category: "Economía",
      text: "El café se consolida definitivamente como el principal producto de exportación de Colombia. La economía nacional comienza a depender en gran medida de este cultivo, lo que genera crecimiento económico en varias regiones." },
    mundo: { title: "Hundimiento del Titanic", category: "Desastre",
      text: "Se hundió el RMS Titanic en su viaje inaugural, causando más de 1.500 muertes." } },
  { year: 1914,
    colombia: { title: "Apertura del Canal de Panamá", category: "Economía",
      text: "La apertura del Canal de Panamá transforma las rutas comerciales del continente. Aunque Colombia había perdido Panamá en 1903, el canal influye significativamente en el comercio y las relaciones económicas de la región." },
    mundo: { title: "Estalla la Primera Guerra Mundial", category: "Conflicto",
      text: "Comenzó la Primera Guerra Mundial, uno de los conflictos más importantes de la historia." } },
  { year: 1916,
    colombia: { title: "Crecimiento de las exportaciones cafeteras", category: "Economía",
      text: "Las exportaciones cafeteras continúan creciendo y fortalecen la economía nacional. Varias regiones productoras experimentan desarrollo económico y expansión de sus actividades comerciales." },
    mundo: { title: "Continúa la Gran Guerra", category: "Conflicto",
      text: "La Primera Guerra Mundial continuó con intensos combates y millones de víctimas en Europa." } },
  { year: 1918,
    colombia: { title: "Llega la gripe española", category: "Salud",
      text: "La pandemia de [[gripe española]] llega al país y afecta a miles de personas. Los servicios de salud enfrentan dificultades para atender a la población, generándose una importante crisis sanitaria." },
    mundo: { title: "Fin de la guerra y pandemia mundial", category: "Salud",
      text: "Terminó la Primera Guerra Mundial y se propagó la [[gripe española]], que afectó a millones de personas." } },
  { year: 1920,
    colombia: { title: "Auge cafetero", category: "Economía",
      text: "Gracias al auge del café, Colombia vive un período de crecimiento económico. El comercio exterior se fortalece y aumentan las inversiones en infraestructura y transporte." },
    mundo: { title: "Se crea la Sociedad de Naciones", category: "Política",
      text: "Se creó la [[Sociedad de Naciones]] con el objetivo de mantener la paz mundial." } },
  { year: 1922,
    colombia: { title: "Reformas financieras", category: "Economía",
      text: "El gobierno implementa reformas financieras para modernizar la economía. Se fortalecen las instituciones bancarias y se busca mejorar la organización del sistema monetario nacional." },
    mundo: { title: "Se funda la Unión Soviética", category: "Política",
      text: "Se fundó la Unión de Repúblicas Socialistas Soviéticas, convirtiéndose en una de las principales potencias del siglo XX." } },
  { year: 1924,
    colombia: { title: "Inversión en ferrocarriles y carreteras", category: "Economía",
      text: "Continúan las inversiones en ferrocarriles, carreteras y sistemas de comunicación. Estas obras contribuyen a integrar mejor las distintas regiones del país y facilitar el comercio." },
    mundo: { title: "Juegos Olímpicos de 1924", category: "Cultura",
      text: "Los Juegos Olímpicos de verano de 1924 impulsaron el crecimiento del deporte internacional." } },
  { year: 1926,
    colombia: { title: "Modernización en marcha", category: "Economía",
      text: "El país continúa su proceso de modernización económica e institucional, en un contexto de bonanza cafetera y expansión de las obras públicas." },
    mundo: { title: "La radio se consolida", category: "Tecnología",
      text: "La radio se consolidó como uno de los principales medios de comunicación en el mundo." } },
  { year: 1928,
    colombia: { title: "Masacre de las Bananeras", category: "Sociedad",
      text: "Ocurre la Masacre de las Bananeras, cuando trabajadores de la industria bananera que estaban en huelga son reprimidos por el ejército. Este hecho genera una gran controversia nacional e internacional y se convierte en un símbolo de las luchas laborales en Colombia." },
    mundo: { title: "Fleming descubre la penicilina", category: "Ciencia",
      text: "Alexander Fleming descubrió la penicilina, uno de los avances médicos más importantes de la historia." } },
  { year: 1930,
    colombia: { title: "Fin de la hegemonía conservadora", category: "Política",
      text: "Termina la [[hegemonía conservadora]] que había durado más de cuarenta años. Con la llegada de gobiernos liberales comienza una nueva etapa política caracterizada por reformas sociales, económicas y educativas." },
    mundo: { title: "Comienza la Gran Depresión", category: "Economía",
      text: "Comenzó la [[Gran Depresión]], una grave crisis económica que afectó a gran parte del mundo." } },
  { year: 1932,
    colombia: { title: "Conflicto con el Perú por Leticia", category: "Conflicto",
      text: "Se produce un conflicto armado con el Perú por territorios amazónicos cercanos a Leticia. Colombia moviliza fuerzas militares para defender la región y finalmente logra recuperar el control del territorio en disputa." },
    mundo: { title: "La Gran Depresión se agrava", category: "Economía",
      text: "La [[Gran Depresión]] continuó afectando la economía mundial con desempleo y pobreza." } },
  { year: 1934,
    colombia: { title: "La Revolución en Marcha", category: "Política",
      text: "Bajo el gobierno de Alfonso López Pumarejo se desarrolla la llamada \"[[Revolución en Marcha]]\". Este programa impulsa reformas agrarias, laborales y educativas destinadas a modernizar el país y mejorar las condiciones de vida de la población." },
    mundo: { title: "Avance de gobiernos autoritarios", category: "Política",
      text: "Se fortalecieron los gobiernos autoritarios en varios países de Europa, aumentando las tensiones internacionales." } },
  { year: 1936,
    colombia: { title: "Reforma constitucional de 1936", category: "Política",
      text: "Se aprueban importantes reformas constitucionales que fortalecen el papel del Estado en la economía y reconocen nuevos derechos sociales. Estas medidas representan cambios significativos en la estructura política colombiana." },
    mundo: { title: "Estalla la Guerra Civil Española", category: "Conflicto",
      text: "Comenzó la Guerra Civil Española, un conflicto que tuvo gran impacto en Europa." } },
  { year: 1938,
    colombia: { title: "Continúa la modernización estatal", category: "Educación",
      text: "Continúan las políticas de modernización estatal. Se amplían programas educativos, se fortalecen instituciones públicas y se promueve el desarrollo económico en distintas regiones." },
    mundo: { title: "Acuerdos de Múnich", category: "Política",
      text: "Ocurrió el [[Acuerdos de Múnich|Acuerdo de Múnich]], mediante el cual Alemania obtuvo parte de Checoslovaquia." } },
  { year: 1940,
    colombia: { title: "Efectos indirectos de la guerra mundial", category: "Economía",
      text: "Colombia vive los efectos indirectos de la Segunda Guerra Mundial. Aunque no participa directamente en los combates, el conflicto influye en la economía y las relaciones internacionales del país." },
    mundo: { title: "La guerra se extiende por Europa", category: "Conflicto",
      text: "La Segunda Guerra Mundial se extendió por Europa con importantes invasiones y enfrentamientos militares." } },
  { year: 1942,
    colombia: { title: "Tensión política y cambio social", category: "Política",
      text: "Persisten las tensiones políticas entre liberales y conservadores. Al mismo tiempo, el país continúa experimentando cambios sociales y económicos impulsados por los procesos de modernización." },
    mundo: { title: "Momentos críticos de la guerra mundial", category: "Conflicto",
      text: "La Segunda Guerra Mundial alcanzó uno de sus momentos más intensos con grandes batallas en Europa, África y el Pacífico." } },
  { year: 1944,
    colombia: { title: "Intento de golpe contra López Pumarejo", category: "Política",
      text: "Se presenta un intento de golpe de Estado contra el presidente Alfonso López Pumarejo. Aunque el gobierno logra mantenerse, el hecho demuestra la creciente polarización política existente en el país." },
    mundo: { title: "Desembarco de Normandía", category: "Conflicto",
      text: "Ocurrió el [[desembarco de Normandía]], una operación clave para la liberación de Europa del dominio nazi." } },
  { year: 1946,
    colombia: { title: "Regreso conservador al poder", category: "Política",
      text: "Los conservadores regresan al poder después de varios años de gobiernos liberales. La división política aumenta y comienzan a registrarse enfrentamientos más frecuentes entre simpatizantes de ambos partidos." },
    mundo: { title: "Se crea el UNICEF", category: "Sociedad",
      text: "Se creó el Fondo de las Naciones Unidas para la Infancia (UNICEF) para ayudar a los niños afectados por la guerra." } },
  { year: 1948,
    colombia: { title: "El Bogotazo", category: "Conflicto",
      text: "El asesinato de Jorge Eliécer Gaitán provoca el [[Bogotazo]], una serie de disturbios y actos de violencia en Bogotá que rápidamente se extienden a otras regiones. Este hecho marca el inicio de una etapa conocida como [[La Violencia]]." },
    mundo: { title: "Nace la Organización Mundial de la Salud", category: "Salud",
      text: "La Organización Mundial de la Salud inició sus actividades para promover la salud a nivel mundial." } },
  { year: 1950,
    colombia: { title: "La Violencia se intensifica", category: "Conflicto",
      text: "[[La Violencia]] alcanza niveles muy altos en diversas zonas rurales. Miles de personas son desplazadas y numerosas comunidades resultan afectadas por los enfrentamientos políticos entre liberales y conservadores." },
    mundo: { title: "Estalla la Guerra de Corea", category: "Conflicto",
      text: "Comenzó la Guerra de Corea, uno de los principales conflictos de la Guerra Fría." } },
  { year: 1952,
    colombia: { title: "Expansión de los enfrentamientos", category: "Conflicto",
      text: "Los conflictos continúan expandiéndose en varias regiones. La situación de inseguridad preocupa al gobierno y a la población, mientras aumenta el número de víctimas y desplazados." },
    mundo: { title: "Isabel II asciende al trono", category: "Política",
      text: "Elizabeth II ascendió al trono del Reino Unido." } },
  { year: 1954,
    colombia: { title: "Voto femenino en Colombia", category: "Sociedad",
      text: "Durante el gobierno de Gustavo Rojas Pinilla, las mujeres obtienen oficialmente el derecho al voto. Este acontecimiento representa un avance fundamental en la ampliación de los derechos políticos en Colombia." },
    mundo: { title: "Fin de la guerra de Indochina", category: "Conflicto",
      text: "Terminó la Primera Guerra de Indochina, lo que llevó a la división de Vietnam." } },
  { year: 1956,
    colombia: { title: "Obras públicas y censura", category: "Política",
      text: "El gobierno impulsa obras de infraestructura, carreteras y proyectos de modernización. Sin embargo, también enfrenta críticas por restricciones a las libertades políticas y de prensa." },
    mundo: { title: "Crisis del Canal de Suez", category: "Conflicto",
      text: "Ocurrió la Crisis de Suez, un conflicto que tuvo gran impacto en la política internacional." } },
  { year: 1958,
    colombia: { title: "Comienza el Frente Nacional", category: "Política",
      text: "Comienza el [[Frente Nacional]], acuerdo mediante el cual liberales y conservadores se alternan la presidencia y comparten cargos públicos para poner fin a la violencia partidista." },
    mundo: { title: "Nace la NASA", category: "Ciencia",
      text: "Se creó la Administración Nacional de Aeronáutica y del Espacio (NASA), impulsando la exploración espacial." } },
  { year: 1960,
    colombia: { title: "Estabilidad con desigualdad", category: "Sociedad",
      text: "Aunque el [[Frente Nacional]] reduce los enfrentamientos entre los partidos tradicionales, continúan existiendo problemas sociales, económicos y de desigualdad que afectan a amplios sectores de la población." },
    mundo: { title: "El Año de África", category: "Política",
      text: "Fue conocido como el “Año de África” porque 17 países africanos lograron su independencia." } },
  { year: 1962,
    colombia: { title: "Persisten la pobreza rural y la desigualdad", category: "Sociedad",
      text: "Persisten los problemas relacionados con la distribución de tierras, la pobreza rural y la falta de oportunidades en muchas regiones. Aunque el [[Frente Nacional]] mantiene cierta estabilidad política, algunos grupos consideran que el sistema limita la participación democrática de otros sectores." },
    mundo: { title: "Crisis de los Misiles de Cuba", category: "Conflicto",
      text: "Ocurrió la [[Crisis de los Misiles de Cuba]], uno de los momentos más tensos de la Guerra Fría." } },
  { year: 1964,
    colombia: { title: "Surgen las FARC", category: "Conflicto",
      text: "Surgen las [[FARC]] tras operaciones militares en zonas rurales. Este hecho marca el inicio de una nueva etapa del conflicto armado colombiano, que se prolongaría durante varias décadas y tendría profundas consecuencias sociales y económicas." },
    mundo: { title: "Juegos Olímpicos de Tokio", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 1964, los primeros realizados en Asia." } },
  { year: 1966,
    colombia: { title: "Expansión del conflicto armado", category: "Conflicto",
      text: "El conflicto armado comienza a expandirse lentamente. Además de las [[FARC]], otros grupos insurgentes fortalecen su presencia en diferentes regiones del país, mientras el gobierno intenta mantener el control del territorio." },
    mundo: { title: "Mundial de fútbol en Inglaterra", category: "Cultura",
      text: "Se realizó la Copa Mundial de la FIFA de 1966 en Inglaterra, ganada por el país anfitrión." } },
  { year: 1968,
    colombia: { title: "Reforma constitucional de 1968", category: "Política",
      text: "Se aprueba una reforma constitucional que busca modernizar las instituciones estatales y mejorar la administración pública. También se fortalecen algunas funciones del gobierno nacional para enfrentar los nuevos desafíos políticos y sociales." },
    mundo: { title: "Año de protestas globales", category: "Sociedad",
      text: "Fue un año de protestas estudiantiles y movimientos sociales en varios países del mundo." } },
  { year: 1970,
    colombia: { title: "Elecciones controvertidas", category: "Política",
      text: "Las elecciones presidenciales generan una fuerte controversia debido a denuncias de fraude electoral. El descontento político de algunos sectores contribuye posteriormente al surgimiento de nuevos movimientos insurgentes y de oposición." },
    mundo: { title: "Mundial de fútbol en México", category: "Cultura",
      text: "Se celebró la Copa Mundial de la FIFA de 1970 en México, considerada una de las más importantes de la historia del fútbol." } },
  { year: 1972,
    colombia: { title: "Crecimiento urbano acelerado", category: "Sociedad",
      text: "Las principales ciudades colombianas experimentan un rápido crecimiento urbano. Miles de personas migran desde las zonas rurales hacia centros urbanos en busca de empleo, educación y mejores condiciones de vida." },
    mundo: { title: "Juegos Olímpicos de Múnich", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 1972, marcados por un ataque terrorista contra atletas israelíes." } },
  { year: 1974,
    colombia: { title: "Fin del Frente Nacional", category: "Política",
      text: "Finaliza oficialmente el [[Frente Nacional]]. A partir de este momento se restablece plenamente la competencia electoral entre diferentes partidos y movimientos políticos, ampliando la participación democrática." },
    mundo: { title: "Renuncia de Nixon", category: "Política",
      text: "Ocurrió la renuncia de Richard Nixon debido al escándalo Watergate." } },
  { year: 1976,
    colombia: { title: "Industrialización y crecimiento urbano", category: "Economía",
      text: "El país continúa su proceso de industrialización y modernización económica. Se desarrollan sectores manufactureros y aumenta la importancia de las ciudades como centros económicos y administrativos." },
    mundo: { title: "Juegos Olímpicos de Montreal", category: "Cultura",
      text: "Se realizaron los Juegos Olímpicos de verano de 1976 en Canadá." } },
  { year: 1978,
    colombia: { title: "Aumenta la complejidad del conflicto", category: "Conflicto",
      text: "Los problemas de seguridad se vuelven más complejos debido al crecimiento de grupos armados ilegales y al aumento de actividades relacionadas con el narcotráfico. El Estado enfrenta nuevos desafíos para garantizar el orden público." },
    mundo: { title: "Acuerdos de Camp David", category: "Política",
      text: "Se firmaron los [[Acuerdos de Camp David]], un importante paso hacia la paz entre Egipto e Israel." } },
  { year: 1980,
    colombia: { title: "Auge del narcotráfico", category: "Conflicto",
      text: "El narcotráfico adquiere una enorme influencia económica y criminal. Organizaciones dedicadas al tráfico de drogas acumulan grandes recursos y comienzan a afectar gravemente la seguridad y la política nacional." },
    mundo: { title: "Guerra Irán-Irak", category: "Conflicto",
      text: "Comenzó la Guerra Irán-Irak, uno de los conflictos más largos del siglo XX." } },
  { year: 1982,
    colombia: { title: "Primeros diálogos con la guerrilla", category: "Política",
      text: "El gobierno inicia algunos intentos de diálogo con grupos guerrilleros para buscar soluciones negociadas al conflicto armado. Aunque existen avances iniciales, las dificultades para alcanzar acuerdos definitivos son significativas." },
    mundo: { title: "Guerra de las Malvinas", category: "Conflicto",
      text: "Ocurrió la Guerra de las Malvinas entre Argentina y el Reino Unido." } },
  { year: 1984,
    colombia: { title: "Acuerdos de cese al fuego", category: "Conflicto",
      text: "Se firman acuerdos de cese al fuego con algunos grupos insurgentes. Sin embargo, la violencia no desaparece y continúan ocurriendo enfrentamientos en distintas regiones del país." },
    mundo: { title: "Juegos Olímpicos de Los Ángeles", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 1984." } },
  { year: 1986,
    colombia: { title: "Escalada del narcotráfico", category: "Conflicto",
      text: "La violencia relacionada con el narcotráfico y el conflicto armado aumenta considerablemente. Los carteles de la droga adquieren mayor poder y desafían abiertamente a las instituciones del Estado." },
    mundo: { title: "Desastre de Chernóbil", category: "Desastre",
      text: "Ocurrió el [[desastre de Chernóbil]], uno de los mayores desastres nucleares de la historia." } },
  { year: 1988,
    colombia: { title: "Elección popular de alcaldes", category: "Política",
      text: "Se implementa la elección popular de alcaldes, una reforma importante para fortalecer la descentralización y la participación ciudadana en los asuntos locales." },
    mundo: { title: "Acuerdos al final de la Guerra Fría", category: "Política",
      text: "Se firmaron acuerdos para poner fin a varios conflictos relacionados con la Guerra Fría." } },
  { year: 1990,
    colombia: { title: "Camino hacia la Constituyente", category: "Política",
      text: "Se desarrolla un proceso de transformación política que impulsa la convocatoria de una [[Asamblea Constituyente]]. Diversos sectores consideran necesario modernizar el sistema político y ampliar los derechos ciudadanos." },
    mundo: { title: "Estalla la Guerra del Golfo", category: "Conflicto",
      text: "Comenzó la Guerra del Golfo tras la invasión de Kuwait por Irak." } },
  { year: 1992,
    colombia: { title: "Desarrollo bajo la nueva Constitución", category: "Política",
      text: "Tras la promulgación de la Constitución de 1991, el país comienza a desarrollar nuevas instituciones y mecanismos de participación ciudadana, en un contexto donde persisten los retos del conflicto armado." },
    mundo: { title: "Juegos Olímpicos de Barcelona", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 1992, un evento que marcó una nueva etapa del deporte internacional." } },
  { year: 1994,
    colombia: { title: "Desafíos persistentes pese a las reformas", category: "Conflicto",
      text: "A pesar de los avances institucionales, continúan los desafíos relacionados con el conflicto armado, el narcotráfico y la violencia en distintas regiones." },
    mundo: { title: "Fin del Apartheid", category: "Política",
      text: "Terminó el [[Apartheid]] y Nelson Mandela fue elegido presidente." } },
  { year: 1996,
    colombia: { title: "Intensificación de la violencia rural", category: "Conflicto",
      text: "Las acciones de grupos armados ilegales aumentan en intensidad. Muchas comunidades rurales resultan afectadas por enfrentamientos, desplazamientos y problemas de seguridad." },
    mundo: { title: "Juegos Olímpicos de Atlanta", category: "Cultura",
      text: "Se realizaron los Juegos Olímpicos de verano de 1996 en Estados Unidos." } },
  { year: 1998,
    colombia: { title: "Proceso de paz del Caguán", category: "Política",
      text: "Se inicia un nuevo proceso de paz con las [[FARC]] en la zona del Caguán. El gobierno busca una solución negociada al conflicto, aunque las conversaciones enfrentan múltiples dificultades." },
    mundo: { title: "Nace Google", category: "Tecnología",
      text: "Se lanzó Google, que transformó la búsqueda de información en internet." } },
  { year: 2000,
    colombia: { title: "Plan Colombia", category: "Política",
      text: "Se pone en marcha el [[Plan Colombia]], una estrategia apoyada internacionalmente para combatir el narcotráfico, fortalecer las instituciones y mejorar la seguridad nacional." },
    mundo: { title: "Llegada del nuevo milenio", category: "Tecnología",
      text: "El mundo celebró la llegada del nuevo milenio y continuó el crecimiento de internet y las nuevas tecnologías." } },
  { year: 2002,
    colombia: { title: "Gobierno de Uribe y Seguridad Democrática", category: "Política",
      text: "Comienza el gobierno de Álvaro Uribe Vélez. Su política de [[Seguridad Democrática]] busca recuperar el control territorial y reducir la capacidad militar de los grupos armados ilegales." },
    mundo: { title: "Mundial de fútbol en Asia", category: "Cultura",
      text: "Se celebró la Copa Mundial de la FIFA de 2002 en Corea del Sur y Japón, la primera realizada en Asia." } },
  { year: 2004,
    colombia: { title: "Intensificación de operaciones militares", category: "Conflicto",
      text: "Las operaciones militares se intensifican y el Estado aumenta su presencia en regiones que habían estado fuertemente afectadas por el conflicto armado." },
    mundo: { title: "Tsunami del Océano Índico", category: "Desastre",
      text: "Ocurrió el terremoto y tsunami del Océano Índico de 2004, uno de los desastres naturales más devastadores de la historia." } },
  { year: 2006,
    colombia: { title: "Reelección de Uribe", category: "Política",
      text: "Uribe es reelegido presidente. Durante este período continúan las estrategias de seguridad y se desarrollan procesos de desmovilización con algunos grupos armados." },
    mundo: { title: "Nace Twitter", category: "Tecnología",
      text: "Se lanzó Twitter, que se convirtió en una de las plataformas de comunicación más influyentes." } },
  { year: 2008,
    colombia: { title: "Operación Jaque", category: "Conflicto",
      text: "La [[Operación Jaque]] permite el rescate de varios secuestrados retenidos por las FARC, entre ellos la ex candidata presidencial Íngrid Betancourt. La operación recibe reconocimiento internacional." },
    mundo: { title: "Comienza la Gran Recesión", category: "Economía",
      text: "Comenzó la Gran Recesión, afectando economías de todo el mundo." } },
  { year: 2010,
    colombia: { title: "Gobierno de Santos", category: "Política",
      text: "Inicia el gobierno de Juan Manuel Santos. Su administración impulsa políticas de desarrollo social y abre el camino para nuevas negociaciones de paz." },
    mundo: { title: "Mundial de fútbol en Sudáfrica", category: "Cultura",
      text: "Se celebró la Copa Mundial de la FIFA de 2010 en Sudáfrica, la primera realizada en África." } },
  { year: 2012,
    colombia: { title: "Inician los diálogos de La Habana", category: "Política",
      text: "Comienzan oficialmente en La Habana las conversaciones de paz entre el gobierno colombiano y las FARC. El proceso busca poner fin a más de medio siglo de conflicto armado." },
    mundo: { title: "Juegos Olímpicos de Londres", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 2012." } },
  { year: 2014,
    colombia: { title: "Avances en las negociaciones de paz", category: "Política",
      text: "Las negociaciones continúan avanzando. Aunque existen debates y diferencias entre distintos sectores políticos, se logran acuerdos parciales en varios temas fundamentales." },
    mundo: { title: "Mundial de fútbol en Brasil", category: "Cultura",
      text: "Se realizó la Copa Mundial de la FIFA de 2014 en Brasil." } },
  { year: 2016,
    colombia: { title: "Acuerdo de Paz con las FARC", category: "Política",
      text: "Se firma el Acuerdo de Paz entre el gobierno y las [[FARC]]. Este acontecimiento representa uno de los hechos más importantes de la historia reciente de Colombia y abre una nueva etapa orientada hacia la reconciliación y la construcción de paz." },
    mundo: { title: "Reino Unido vota el Brexit", category: "Política",
      text: "El Reino Unido votó a favor del [[Brexit]], iniciando su salida de la Unión Europea." } },
  { year: 2018,
    colombia: { title: "Gobierno de Iván Duque", category: "Política",
      text: "Es elegido presidente Iván Duque Márquez. Su gobierno enfrenta desafíos relacionados con la implementación de los acuerdos de paz, la economía y la seguridad." },
    mundo: { title: "Avances en inteligencia artificial", category: "Tecnología",
      text: "Se realizaron importantes avances en inteligencia artificial y tecnología digital a nivel mundial." } },
  { year: 2020,
    colombia: { title: "Pandemia de COVID-19 en Colombia", category: "Salud",
      text: "La pandemia de COVID-19 afecta profundamente al país. Se implementan medidas de confinamiento, la economía sufre una fuerte desaceleración y los sistemas de salud enfrentan grandes desafíos." },
    mundo: { title: "Pandemia de COVID-19 mundial", category: "Salud",
      text: "La pandemia de COVID-19 afectó al mundo entero, causando una crisis sanitaria, económica y social." } },
  { year: 2022,
    colombia: { title: "Gustavo Petro, primer presidente de izquierda", category: "Política",
      text: "Es elegido presidente Gustavo Petro, convirtiéndose en el primer mandatario de izquierda elegido democráticamente en la historia del país. Su gobierno propone reformas en áreas como salud, trabajo, educación y transición energética." },
    mundo: { title: "Invasión rusa a Ucrania", category: "Conflicto",
      text: "Comenzó la invasión rusa de Ucrania, uno de los conflictos internacionales más importantes de los últimos años." } },
  { year: 2024,
    colombia: { title: "Debates sobre la paz total y las reformas", category: "Política",
      text: "Continúan los debates nacionales sobre reformas sociales, económicas y ambientales. El gobierno impulsa políticas relacionadas con la [[paz total]], la protección ambiental y la reducción de desigualdades, mientras enfrenta importantes discusiones en el Congreso." },
    mundo: { title: "Juegos Olímpicos de París", category: "Cultura",
      text: "Se celebraron los Juegos Olímpicos de verano de 2024 y continuó el rápido desarrollo de la inteligencia artificial en todo el mundo." } },
  { year: 2026,
    colombia: { title: "Retos de seguridad y elecciones", category: "Política",
      text: "Colombia continúa enfrentando desafíos en seguridad, economía y paz. También siguen los debates sobre las reformas del gobierno de Gustavo Petro y la preparación para las elecciones nacionales, mientras se impulsan proyectos de desarrollo sostenible y transición energética." },
    mundo: { title: "Mundial de fútbol 2026", category: "Cultura",
      text: "Se celebra la Copa Mundial de la FIFA de 2026 en Estados Unidos, Canadá y México, mientras la inteligencia artificial sigue transformando la educación, el trabajo y la tecnología." } }
];

const CATEGORIAS = ["Política", "Conflicto", "Economía", "Sociedad", "Educación", "Tecnología", "Cultura", "Ciencia", "Salud", "Desastre"];
